# Generated by Django 5.1.5 on 2025-02-06 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 16, 40, 29, 841442, tzinfo=datetime.timezone.utc)),
        ),
    ]
