# Generated by Django 5.1.5 on 2025-02-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=50)),
                ('std_lastname', models.CharField(max_length=50)),
                ('std_address', models.CharField(max_length=50)),
            ],
        ),
    ]
